export enum AuthTypes {
  LOGIN_REQUEST = "@auth/LOGIN_REQUEST",
  LOGIN_SUCCESS = "@auth/LOGIN_SUCCESS",
  LOGIN_ERROR = "@auth/LOGIN_ERROR",
  LOGOUT = "@auth/LOGOUT",
  LOGOUT_SUCCESS = "@auth/LOGOUT_SUCCESS",
  LOGOUT_ERROR = "@auth/LOGOUT_ERROR",
  REGISTER_REQUEST = "@auth/REGISTER_REQUEST",
  REGISTER_SUCCESS = "@auth/REGISTER_SUCCESS",
  REGISTER_ERROR = "@auth/REGISTER_ERROR",
  SET_FIRST_LOGIN = "@auth/SET_FIRST_LOGIN",
}
